RDKCOM-2207: RDKBDEV-469: fix memset with sizeof pointer
Reason for change:
fix memset with sizeof pointer in mbiIf_SendParameterValueChangeSignal()
 | .../source/ccsp/components/common/MessageBusHelper/helper/messagebus_interface_utility.c: In function 'mbiIf_SendParameterValueChangeSignal':
 | .../source/ccsp/components/common/MessageBusHelper/helper/messagebus_interface_utility.c:169:41: error: argument to 'sizeof' in 'memset' call is the same pointer type 'parameterSigStruct_t *' {aka 'struct <anonymous> *'} as the destination; expected 'parameterSigStruct_t' {aka 'struct <anonymous>'} or an explicit length [-Werror=sizeof-pointer-memaccess]
 |   169 |     AnscZeroMemory(pParamSignal, sizeof(parameterSigStruct_t*));
 |       |                                         ^~~~~~~~~~~~~~~~~~~~
 | .../source/debug_api/include/ccsp_memory.h:133:42: note: in definition of macro 'AnscZeroMemory'
 |   133 |             (void) memset((pMemory), 0, (size))
 |       |                                          ^~~~
Test Procedure: Basic Sanity
Risks: None.
Signed-off-by: Andre McCurdy <armccurdy@gmail.com>

(cherry picked from commit c2eb68373356f1f6813b94268001ce486627dd5a)
Change-Id: Idf416a2d143527f539ea61280d2dff7407aa522f